import { Servicio, Especialidad } from "./types";
import { 
  Stethoscope, Microscope, Truck, Scan, Activity, 
  Waves, Scissors, Bed, HeartPulse, Pill, Droplets,
  Syringe, Heart, UserRound, Ribbon, Baby, 
  Sparkles, Scale, Utensils, Venus, 
  Accessibility, Hospital, Droplet, Wind, Brain, 
  Zap, Smile, Eye, Bone 
} from "lucide-react"

export const servicios: Servicio[] = [
  {
    id: 1,
    titulo: "Consulta Externa",
    descripcion: "Atención médica especializada para el diagnóstico y tratamiento integral de diversas patologías.",
    icono: Stethoscope,
  },
  {
    id: 2,
    titulo: "Laboratorio Clínico",
    descripcion: "Análisis de alta precisión con tecnología de vanguardia para resultados rápidos y confiables.",
    icono: Microscope,
  },
  {
    id: 3,
    titulo: "Emergencias 24/7",
    descripcion: "Atención inmediata y especializada para urgencias médicas en cualquier momento del día.",
    icono: Truck,
  },
  {
    id: 4,
    titulo: "Tomografía",
    descripcion: "Estudios de imagen avanzados para diagnósticos detallados mediante escaneo de alta resolución.",
    icono: Scan,
  },
  {
    id: 5,
    titulo: "Rayos X",
    descripcion: "Servicio de radiología digital para la evaluación precisa de estructuras óseas y órganos internos.",
    icono: Activity,
  },
  {
    id: 6,
    titulo: "Ecografía",
    descripcion: "Diagnóstico por ultrasonido no invasivo para monitoreo clínico y seguimiento especializado.",
    icono: Waves,
  },
  {
    id: 7,
    titulo: "Sala de Operación",
    descripcion: "Quirófanos equipados con tecnología de última generación para procedimientos de alta complejidad.",
    icono: Scissors,
  },
  {
    id: 8,
    titulo: "Hospitalización",
    descripcion: "Habitaciones confortables y atención médica continua para una recuperación segura y monitoreada.",
    icono: Bed,
  },
  {
    id: 9,
    titulo: "UCI",
    descripcion: "Unidad de Cuidados Intensivos con soporte vital avanzado y vigilancia médica especializada 24/7.",
    icono: HeartPulse,
  },
  {
    id: 10,
    titulo: "Farmacia",
    descripcion: "Amplio stock de medicamentos y asesoría farmacéutica para completar su tratamiento.",
    icono: Pill,
  },
  {
    id: 11,
    titulo: "Banco de Sangre",
    descripcion: "Procesamiento y suministro seguro de componentes sanguíneos para procedimientos y emergencias.",
    icono: Droplets,
  }
];


export const especialidades: Especialidad[] = [
  { id: 1, nombre: "Anestesiología", 
    descripcionCorta: "Cuidado y seguridad del paciente durante procedimientos quirúrgicos.", 
    icono: Syringe, 
    disponible: true, 
    slug: "anestesiologia" 
  },
  { id: 2, 
    nombre: "Cardiología", 
    descripcionCorta: "Cuidado experto del corazón y prevención cardiovascular.", 
    icono: Heart, 
    disponible: true, 
    slug: "cardiologia" 
  },
  { id: 3, 
    nombre: "Cirugía de Cabeza y Cuello", 
    descripcionCorta: "Tratamiento quirúrgico de patologías en región cervical y facial.", 
    icono: UserRound, 
    disponible: true, 
    slug: "cirugia-cabeza-cuello" 
  },
  { id: 4, 
    nombre: "Cirugía General", 
    descripcionCorta: "Intervenciones quirúrgicas del aparato digestivo y pared abdominal.", 
    icono: Scissors, 
    disponible: true, 
    slug: "cirugia-general" 
  },
  { id: 5, 
    nombre: "Cirugía Oncológica", 
    descripcionCorta: "Tratamiento quirúrgico especializado de tumores y procesos neoplásicos.", 
    icono: Ribbon, 
    disponible: true, 
    slug: "cirugia-oncologica" 
  },
  { id: 6, 
    nombre: "Cirugía Pediátrica", 
    descripcionCorta: "Cirugía especializada para neonatos, niños y adolescentes.", 
    icono: Baby, 
    disponible: true, 
    slug: "cirugia-pediatrica" 
  },
  { id: 7, 
    nombre: "Cirugía de Tórax y Cardiovascular", 
    descripcionCorta: "Cirugía compleja de pulmones, corazón y grandes vasos.", 
    icono: Activity, 
    disponible: true, 
    slug: "cirugia-torax" 
  },
  { id: 8, 
    nombre: "Dermatología", 
    descripcionCorta: "Expertos en el cuidado, diagnóstico y tratamiento de la piel.", 
    icono: Sparkles, 
    disponible: true, 
    slug: "dermatologia" 
  },
  { id: 9, 
    nombre: "Endocrinología", 
    descripcionCorta: "Tratamiento de trastornos hormonales y del metabolismo.", 
    icono: Scale, 
    disponible: true, 
    slug: "endocrinologia" 
  },
  { id: 10, 
    nombre: "Gastroenterología", 
    descripcionCorta: "Salud del sistema digestivo, estómago e intestinos.", 
    icono: Utensils, 
    disponible: true, 
    slug: "gastroenterologia" 
  },
  { id: 11, 
    nombre: "Ginecología", 
    descripcionCorta: "Cuidado integral de la salud reproductiva de la mujer.", 
    icono: Venus, 
    disponible: true, 
    slug: "ginecologia" 
  },
  { id: 12, 
    nombre:"Hematología", 
    descripcionCorta: "Estudio y tratamiento de las enfermedades de la sangre.", 
    icono: Droplets, 
    disponible: true, 
    slug: "hematologia" 
  },
  { id: 13, 
    nombre: "Infectología", 
    descripcionCorta: "Prevención y tratamiento de enfermedades infecciosas.", 
    icono: Microscope, 
    disponible: true, 
    slug: "infectologia" 
  },
  { id: 14, nombre: "Medicina Física y Rehabilitación", 
    descripcionCorta: "Recuperación de funciones motoras y terapia física.", 
    icono: Accessibility, 
    disponible: true, 
    slug: "rehabilitacion" 
  },
  { id: 15, 
    nombre: "Medicina Interna", 
    descripcionCorta: "Atención integral del adulto y diagnóstico de enfermedades complejas.", 
    icono: Stethoscope, 
    disponible: true, 
    slug: "medicina-interna" 
  },
  { id: 16, 
    nombre: "Medicina Intensiva - UCI", 
    descripcionCorta: "Cuidados críticos para pacientes en estado delicado.", 
    icono: Hospital, 
    disponible: true, 
    slug: "uci" 
  },
  { id: 17, 
    nombre: "Nefrología", 
    descripcionCorta: "Especialistas en la salud y función de los riñones.", 
    icono: Droplet, 
    disponible: true, 
    slug: "nefrologia" 
  },
  { id: 18, 
    nombre: "Neumología", 
    descripcionCorta: "Cuidado del sistema respiratorio y enfermedades pulmonares.", 
    icono: Wind, 
    disponible: true, 
    slug: "neumologia" 
  },
  { id: 19, 
    nombre: "Neurocirugía", 
    descripcionCorta: "Cirugía especializada del cerebro y sistema nervioso.", 
    icono: Brain, 
    disponible: true, 
    slug: "neurocirugia" 
  },
  { id: 20, 
    nombre: "Neurología", 
    descripcionCorta: "Diagnóstico de trastornos cerebrales y del sistema nervioso.", 
    icono: Zap, 
    disponible: true, 
    slug: "neurologia" 
  },
  { id: 21, 
    nombre: "Odontología", 
    descripcionCorta: "Salud dental integral y estética bucal.", 
    icono: Smile, 
    disponible: true, 
    slug: "odontologia" 
  },
  { id: 22, 
    nombre: "Oftalmología", 
    descripcionCorta: "Cuidado de la visión y tratamiento de enfermedades oculares.", 
    icono: Eye, 
    disponible: true, 
    slug: "oftalmologia" 
  },
  { id: 23, nombre: "Oncología Clínica", 
    descripcionCorta: "Tratamiento médico especializado contra el cáncer.", 
    icono: Ribbon, 
    disponible: true, 
    slug: "oncologia" 
  },
  { id: 24, 
    nombre: "Pediatría", 
    descripcionCorta: "Atención médica integral para bebés y niños.", 
    icono: Baby, 
    disponible: true, 
    slug: "pediatria" 
  },
  { id: 25, 
    nombre: "Psicología", 
    descripcionCorta: "Apoyo emocional y bienestar de la salud mental.", 
    icono: Brain, 
    disponible: true, 
    slug: "psicologia" 
  },
  { id: 26, 
    nombre: "Traumatología y Ortopedia", 
    descripcionCorta: "Lesiones óseas, musculares y articulares.", 
    icono: Bone, 
    disponible: true, 
    slug: "traumatologia" 
  },
  { id: 27, 
    nombre: "Urología", 
    descripcionCorta: "Salud del sistema urinario y aparato reproductor masculino.", 
    icono: Droplet, 
    disponible: true, 
    slug: "urologia" 
  }
];